In [1]:
# -*- coding: utf-8 -*-
"""
Created on Mon Mar 18 16:13:41 2019

@author: Natalie
"""

import numpy as np
import pandas as pd
from numpy import random

# client attributes
criteriaList = [" AC ID", "age", "income", "medical diagnosis", "sex", "number of meals", "home situation"]

# create random normal distributions of client attributes
clientAge = random.normal(76, 25, 500)      #list of 500 with mu, std. dev, & num

clientIncome = random.normal(1075, 250, 500)     #client income

clientMealNumber = random.normal(20, 5, 500)    #avg number of meals clients need per month

# lists to hold values of client attributes
clientList = []  

clientSex = []      #sex of the client

clientHome = []     #client's home situation

clientMed = []

# finish creating client attributes
for i in range(0, 500):
    clientList.append("000" + str(i)) 
    clientHome.append(random.choice(["Alone", "Not Alone"], p = [.57, .43]))
    clientMed.append(random.choice(["On Medication", ""], p = [.53, .47]))
    clientSex.append(random.choice(["Female", "Male"], p = [.63, .37]))
    

# convert client attribute lists into a dataframe for export
data = {'AC ID' : clientList, 'Age': clientAge, 'Income': clientIncome, 'Med' : clientMed, 'Sex': clientSex, 'Num Meals': clientMealNumber, 'Home Life' :clientHome}


#data = {'ID' : clientList, }
 
clientData = pd.DataFrame(data)

#client_excel = clientData.to_excel (r'C:\\William\Desktop\qcClient.xlsx', index = None, header=True)


fundList = []


for i in range(0, 10):
    fundList.append("Funding Source" + ' ' + str(i))
    
fundReqList = ["Donor ID", "total num of funds", "num meals per month","reimburse rate per meal", "sex req", "age req", "medical req", "income req", "home sit req"]

#number of meals per month
#reimbursement rate per meal


moneyList = random.normal(50000, 25000, 10)

mealList = np.zeros(10)

rateList = random.normal(5.5, 1.25, 10)

for i in range(0, 10):
    mealList[i] = moneyList[i]/rateList[i]
    
print("Meal List all:", mealList)

sexList = []

ageList = []

medList = []

incomeList = []

homeList = []

# fund requirements 
for i in range(0, len(fundList)):
    ageList.append(random.choice(["N/A", "Over 60"], p = [.5, .5]))
    homeList.append(random.choice(["Alone", "With Others", "N/A"], p = [.4, .2, .4]))
    sexList.append(random.choice(["Female", "Male", "N/A"], p = [.25, .25, .5]))
    medList.append(random.choice(["Medication", "Nothing"], p = [.5, .5]))
    incomeList.append(random.choice(["Less Than 500", "Between 500 and 1000", "Greater than 1000", "N/A"], p = [.25, .25, .25, .25]))

info = {'AD ID' : fundList, 'Total Funds': moneyList, 'Num Meals per Month': mealList, 'Rate per Meal': rateList, 'Sex Req': sexList, 'Age Req': ageList, 'Med Req': medList, 'Income Req': incomeList, 'Home Req': homeList}


donorData = pd.DataFrame(info)

#donor_excel = donorData.to_excel (r'C:\Users\wntan\Desktop\qcDonor.xlsx', index = None, header=True)

Meal List all: [13785.35571029  9292.99962409 17397.29108936  6417.50197072
 13454.68053907  8161.82795487  6054.25464762  6113.51988046
 15786.17640962 15187.34705486]

In [2]:

print(donorData)

              AD ID   Total Funds  Num Meals per Month  Rate per Meal Sex Req  \
0  Funding Source 0  85995.272743         13785.355710       6.238161  Female
1  Funding Source 1  51721.200654          9292.999624       5.565609     N/A
2  Funding Source 2  68171.780684         17397.291089       3.918528    Male
3  Funding Source 3  36231.924849          6417.501971       5.645799     N/A
4  Funding Source 4  85328.699717         13454.680539       6.341934  Female
5  Funding Source 5  41975.693581          8161.827955       5.142928     N/A
6  Funding Source 6  30349.915307          6054.254648       5.012990     N/A
7  Funding Source 7  30168.636342          6113.519880       4.934741     N/A
8  Funding Source 8  63560.674589         15786.176410       4.026350    Male
9  Funding Source 9  68365.451929         15187.347055       4.501474     N/A

   Age Req Med Req            Income Req     Home Req
0      N/A     Yes         Less Than 500          N/A
1      N/A     Yes                   N/A        Alone
2      N/A     Yes         Less Than 500  With Others
3      N/A      No     Greater than 1000        Alone
4  Over 60      No  Between 500 and 1000        Alone
5  Over 60     Yes  Between 500 and 1000          N/A
6  Over 60      No     Greater than 1000          N/A
7  Over 60      No  Between 500 and 1000          N/A
8      N/A     Yes         Less Than 500          N/A
9      N/A     Yes         Less Than 500  With Others

In [3]:
print(clientData)

      AC ID         Age       Income                Med     Sex  Num Meals  \
0      0000   41.524518   954.176491      On Medication  Female  22.789771
1      0001   84.840198  1012.710071      On Medication  Female  22.445156
2      0002  101.608744   857.015403  Not on Medication    Male  19.784536
3      0003   22.525394  1243.726321  Not on Medication  Female  26.756222
4      0004   63.307796  1151.694453  Not on Medication    Male   5.290676
5      0005   66.207286  1162.514500      On Medication    Male  23.587569
6      0006  110.603131   803.937760  Not on Medication    Male  19.855418
7      0007   73.817914  1145.416353  Not on Medication    Male  24.267599
8      0008   46.535389   691.867463  Not on Medication  Female  19.382178
9      0009   58.688554  1208.357572      On Medication    Male  16.924534
10    00010  107.531685  1058.833722      On Medication  Female  18.914254
11    00011   58.707199  1273.868531      On Medication  Female  25.621140
12    00012   41.595474   635.844137      On Medication  Female  23.914758
13    00013   59.948406  1432.499328      On Medication  Female  20.146115
14    00014   95.657844  1166.371650      On Medication  Female  18.092555
15    00015  102.787696   906.165416      On Medication    Male  17.122347
16    00016   61.889807   697.416647  Not on Medication  Female  15.295073
17    00017   63.980073  1061.122078  Not on Medication  Female  19.747661
18    00018   48.704774  1485.699106      On Medication  Female  30.590171
19    00019   53.534865  1050.696108      On Medication  Female  23.414785
20    00020   98.807839  1309.959614  Not on Medication  Female  21.845193
21    00021   25.006545  1079.668885      On Medication  Female  15.888941
22    00022   82.778058  1098.776912  Not on Medication  Female  25.429629
23    00023   61.769220  1070.104030  Not on Medication  Female  24.313077
24    00024   73.017969   960.426225  Not on Medication    Male  17.980228
25    00025   72.983348   811.973345      On Medication    Male  14.601783
26    00026   56.572829  1408.408596      On Medication  Female  30.092198
27    00027   50.148599   931.608091      On Medication  Female  22.629393
28    00028   62.823334   889.981127      On Medication  Female  13.784784
29    00029   50.382564  1561.972054      On Medication  Female  26.074144
..      ...         ...          ...                ...     ...        ...
470  000470  122.158140  1449.243645  Not on Medication    Male  22.499719
471  000471   90.707239  1064.050299  Not on Medication  Female  19.040098
472  000472  107.992155  1463.702569      On Medication  Female  19.376539
473  000473  104.926597  1110.856921      On Medication    Male  17.081790
474  000474  109.898604   814.537774      On Medication    Male  14.867429
475  000475   95.360256  1247.909053  Not on Medication    Male  21.770231
476  000476   79.261063   972.316352      On Medication  Female  19.012707
477  000477   56.013896   925.104277      On Medication  Female  29.329824
478  000478   81.476038  1322.667495  Not on Medication  Female  18.152805
479  000479   51.405506   880.113574      On Medication    Male  24.234682
480  000480   46.892655  1209.060254  Not on Medication  Female  22.222730
481  000481   39.444766  1200.851271  Not on Medication  Female  19.406452
482  000482   80.761822   985.390003      On Medication    Male  22.529553
483  000483  100.109957   751.815284  Not on Medication  Female  17.832152
484  000484  122.942643  1096.445775  Not on Medication  Female  29.627115
485  000485   81.661449   566.030438      On Medication    Male  19.080631
486  000486   49.918955  1079.925759  Not on Medication  Female  25.068787
487  000487   73.055958   945.593134  Not on Medication  Female  16.546776
488  000488   87.800196   499.548604      On Medication    Male  13.753075
489  000489   58.828353  1052.799883  Not on Medication    Male  20.401330
490  000490   85.743764   911.310394  Not on Medication  Female  20.529217
491  000491   38.736974  1032.819057  Not on Medication  Female  18.871824
492  000492  113.033446   709.894490      On Medication  Female  18.104881
493  000493   49.488730  1403.380931      On Medication  Female  26.326570
494  000494   55.054469  1180.687258      On Medication    Male  23.364269
495  000495  116.120627  1078.765175      On Medication    Male  18.877203
496  000496   77.476224  1053.444392  Not on Medication  Female  18.323082
497  000497  115.980403   662.021336  Not on Medication  Female  17.111617
498  000498  110.774889   859.872462  Not on Medication    Male  24.882218
499  000499   98.490378   955.034279      On Medication  Female  26.610636

     Home Life
0    Not Alone
1        Alone
2        Alone
3        Alone
4        Alone
5        Alone
6    Not Alone
7        Alone
8    Not Alone
9    Not Alone
10       Alone
11       Alone
12       Alone
13       Alone
14       Alone
15   Not Alone
16       Alone
17   Not Alone
18   Not Alone
19       Alone
20   Not Alone
21       Alone
22   Not Alone
23       Alone
24       Alone
25   Not Alone
26   Not Alone
27       Alone
28       Alone
29   Not Alone
..         ...
470      Alone
471      Alone
472      Alone
473  Not Alone
474  Not Alone
475  Not Alone
476  Not Alone
477  Not Alone
478  Not Alone
479  Not Alone
480  Not Alone
481  Not Alone
482      Alone
483  Not Alone
484  Not Alone
485      Alone
486      Alone
487      Alone
488  Not Alone
489  Not Alone
490      Alone
491      Alone
492      Alone
493  Not Alone
494      Alone
495      Alone
496  Not Alone
497      Alone
498      Alone
499      Alone

[500 rows x 7 columns]